// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3489.FEMAv2;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.SPI;
import com.kauailabs.navx.frc.AHRS;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX drivebaseMotorFrontLeft;
    public static WPI_TalonSRX drivebaseMotorFrontRight;
    public static DifferentialDrive drivebaseDriveTrain;
    public static WPI_TalonSRX drivebaseMotorRearLeft;
    public static WPI_TalonSRX drivebaseMotorRearRight;
    public static DoubleSolenoid drivebaseRocketBoxShifter;
    public static Encoder drivebaseLeftEnc;
    public static Encoder drivebaseRightEnc;
    public static Solenoid gripperGripper60PSI;
    public static Solenoid gripperGripper20PSI;
    public static DigitalInput gripperAutoGripCube;
    public static WPI_TalonSRX gripperMotorRightIntake;
    public static WPI_TalonSRX gripperMotorLeftIntake;
    public static WPI_TalonSRX lifterMotorLift1;
    public static WPI_TalonSRX lifterMotorLift2;
    public static Solenoid lifterLiftBreak;
    public static DigitalInput autonomousSelectorCh1;
    public static DigitalInput autonomousSelectorCh2;
    public static DigitalInput autonomousSelectorCh3;
    public static DigitalInput autonomousSelectorCh4;
    public static DigitalInput autonomousSelectorCh5;
    public static DigitalInput autonomousSelectorLeftSelect;
    public static DigitalInput autonomousSelectorRightSelect;
    public static Solenoid climberClimberPin;
    public static DigitalInput climberMaximumClimb;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static AHRS navx;
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivebaseMotorFrontLeft = new WPI_TalonSRX(1);
        
        
        drivebaseMotorFrontRight = new WPI_TalonSRX(2);
        
        
        drivebaseDriveTrain = new DifferentialDrive(drivebaseMotorFrontLeft, drivebaseMotorFrontRight);
        LiveWindow.addActuator("Drivebase", "Drive Train", drivebaseDriveTrain);
        drivebaseDriveTrain.setSafetyEnabled(true);
        drivebaseDriveTrain.setExpiration(0.1);
        drivebaseDriveTrain.setMaxOutput(1.0);

        drivebaseMotorRearLeft = new WPI_TalonSRX(3);
        
        
        drivebaseMotorRearRight = new WPI_TalonSRX(4);
        
        
        drivebaseRocketBoxShifter = new DoubleSolenoid(20, 4, 5);
        LiveWindow.addActuator("Drivebase", "Rocket Box Shifter", drivebaseRocketBoxShifter);
        
        drivebaseLeftEnc = new Encoder(4, 5, false, EncodingType.k2X);
        LiveWindow.addSensor("Drivebase", "Left Enc", drivebaseLeftEnc);
        drivebaseLeftEnc.setDistancePerPulse(1.0);
        drivebaseLeftEnc.setPIDSourceType(PIDSourceType.kRate);
        drivebaseRightEnc = new Encoder(6, 7, false, EncodingType.k2X);
        LiveWindow.addSensor("Drivebase", "Right Enc", drivebaseRightEnc);
        drivebaseRightEnc.setDistancePerPulse(1.0);
        drivebaseRightEnc.setPIDSourceType(PIDSourceType.kRate);
        gripperGripper60PSI = new Solenoid(20, 2);
        LiveWindow.addActuator("Gripper", "Gripper 60 PSI", gripperGripper60PSI);
        
        gripperGripper20PSI = new Solenoid(20, 3);
        LiveWindow.addActuator("Gripper", "Gripper 20 PSI", gripperGripper20PSI);
        
        gripperAutoGripCube = new DigitalInput(3);
        LiveWindow.addSensor("Gripper", "Auto Grip Cube", gripperAutoGripCube);
        
        gripperMotorRightIntake = new WPI_TalonSRX(5);
        
        
        gripperMotorLeftIntake = new WPI_TalonSRX(8);
        
        
        lifterMotorLift1 = new WPI_TalonSRX(6);
        
        
        lifterMotorLift2 = new WPI_TalonSRX(7);
        
        
        lifterLiftBreak = new Solenoid(20, 1);
        LiveWindow.addActuator("Lifter", "Lift Break", lifterLiftBreak);
        
        autonomousSelectorCh1 = new DigitalInput(19);
        LiveWindow.addSensor("AutonomousSelector", "Ch 1", autonomousSelectorCh1);
        
        autonomousSelectorCh2 = new DigitalInput(20);
        LiveWindow.addSensor("AutonomousSelector", "Ch 2", autonomousSelectorCh2);
        
        autonomousSelectorCh3 = new DigitalInput(21);
        LiveWindow.addSensor("AutonomousSelector", "Ch 3", autonomousSelectorCh3);
        
        autonomousSelectorCh4 = new DigitalInput(22);
        LiveWindow.addSensor("AutonomousSelector", "Ch 4", autonomousSelectorCh4);
        
        autonomousSelectorCh5 = new DigitalInput(23);
        LiveWindow.addSensor("AutonomousSelector", "Ch 5", autonomousSelectorCh5);
        
        autonomousSelectorLeftSelect = new DigitalInput(10);
        LiveWindow.addSensor("AutonomousSelector", "Left Select", autonomousSelectorLeftSelect);
        
        autonomousSelectorRightSelect = new DigitalInput(11);
        LiveWindow.addSensor("AutonomousSelector", "Right Select", autonomousSelectorRightSelect);
        
        climberClimberPin = new Solenoid(20, 0);
        LiveWindow.addActuator("Climber", "Climber Pin", climberClimberPin);
        
        climberMaximumClimb = new DigitalInput(8);
        LiveWindow.addSensor("Climber", "Maximum Climb", climberMaximumClimb);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        navx = new AHRS(SPI.Port.kMXP);
        
        LiveWindow.add(lifterlifter1);
        LiveWindow.add(lifterlifter2);
        LiveWindow.add(lifterlifterBreak);
        
    }
}
