// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3489.FEMAv2.subsystems;

import org.usfirst.frc3489.FEMAv2.Robot;
import org.usfirst.frc3489.FEMAv2.RobotMap;
import org.usfirst.frc3489.FEMAv2.commands.*;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalInput;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class AutonomousSelection extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DigitalInput leftSelect = RobotMap.autonomousSelectionLeftSelect;
    private final DigitalInput rightSelect = RobotMap.autonomousSelectionRightSelect;
    private final DigitalInput ch1 = RobotMap.autonomousSelectionCh1;
    private final DigitalInput ch2 = RobotMap.autonomousSelectionCh2;
    private final DigitalInput ch3 = RobotMap.autonomousSelectionCh3;
    private final DigitalInput ch4 = RobotMap.autonomousSelectionCh4;
    private final DigitalInput ch5 = RobotMap.autonomousSelectionCh5;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }
    
    public String getSwitch() {
    	if (leftSelect.get() == false) {
    		return "left";
    	} else if (rightSelect.get() == false) {
    		return "right";
    	} else {
    		return "center";
    	}
    }
    /*
    public Command getSwitchPos() {
    	String gameData;
		gameData = DriverStation.getInstance().getGameSpecificMessage();
    	if (leftSelect.get() == false) {
    		if(gameData.charAt(1) == 'L') {
    			//Left Scale Auto
    			return leftAutoScale.;
    		} else {
    			if (gameData.charAt(0) == 'L') {
    				//Left Switch Auto
    				return leftAutoSwitch.class;
    			} else {
    				//Left Other Auto
    				return "leftRightAutoStraight";
    			}
    		}
    	}
    	else if (rightSelect.get() == false) {
    		if(gameData.charAt(0) == 'R') {
    			
    			//Right Switch Auto
    			return "rightAutoSwitch";
    		} else {
    			if (gameData.charAt(1) == 'R') {
    				//Right Scale Auto
    				return "rightAutoScale";
    			} else {
    				//Right Other Auto
    				return "leftRightAutoStraight";
    			}
    		}
    	} else {
    		if(gameData.charAt(0) == 'R') {
    			//Center Right Auto
    			return "centerAutoSwitchRight";
    		} else {
    			//Center Left Auto
    			return "centerAutoSwitchLeft";
    		}
    	}
    }
    */

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

