// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3489.FEMAv2.subsystems;

import org.usfirst.frc3489.FEMAv2.RobotMap;
import org.usfirst.frc3489.FEMAv2.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Solenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Gripper extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double SWITCH_POS = 9000;
    public static final double SCALE_L_POS = 21200;
    public static final double SCALE_H_POS = 27208;
    public static final double LIFTER_TOLERANCE = 10;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DigitalInput autoCube = RobotMap.gripperautoCube;
    private final Solenoid gripper20Psi = RobotMap.gripperGripper20Psi;
    private final Solenoid gripper60Psi = RobotMap.gripperGripper60Psi;
    private final WPI_TalonSRX leftIntake = RobotMap.gripperleftIntake;
    private final WPI_TalonSRX rightIntake = RobotMap.gripperrightIntake;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new GripperMotorControl());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }
    
    /**
     * Closes the gripper and grips the cube with full pressure (60 Psi)
     */
    public void grabCube() {
    	gripper60Psi.set(true);
    	gripper20Psi.set(false);
    }
    
    /**
     * Opens the cube gripper and releases cube
     */
    public void releaseCube() {
    	gripper60Psi.set(false);
    	gripper20Psi.set(true);
    }
    
    public void gripperinout(double speed) {
    	double inputFactor = 1;
    	double motorPower;
    	
    	motorPower = inputFactor * speed;
    	leftIntake.set(-motorPower);
    	rightIntake.set(motorPower);
    }
    
    public void gripperrotate(double speed) {
    	double inputFactor = 1;
    	double motorPower;
    	
    	motorPower = inputFactor * speed;
    	leftIntake.set(motorPower);
    	rightIntake.set(motorPower);
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

